input_data = open('input.txt','r')
data = input_data.read()
output_data = open('output.txt','w')
data=data.split
A=int(data[0])
B=int(data[1])
#e=int(data[2])
output_data.write(str(sum(A,B)))
output_data.close()
input_data.close()